project:
  type: website
  output-dir: docs
  
website:
  title: "Data Science Tools Workshop"
  navbar:
    right:
      - href: Intro_Git_Github.qmd
        text: Slides
      - href: about.qmd
        text: "About the Workshop"
        
format:
  html:
    theme: litera
    css: styles.scss
    toc: true

editor: visual

