project:
  type: website
  output-dir: docs
  
website:
  title: "Data Science Tools Workshop Materials for Lessons on Git and Github"
  navbar:
    left:
      - href: Intro_Git_Github.qmd
        text: Slides
      - href: about.qmd
        text: "About the Workshop"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

