project:
  type: website
  output-dir: docs
  
website:
  title: "Data Science Tools Workshop"
  navbar:
    right:
      - href: index.qmd
        text: "About the Workshop"
      - href: Intro_Git_Github.qmd
        text: "Overeview Presentation Slides"
      - href: GitHubWorkshop.qmd
        text: "Workshop Slides"
        
format:
  html:
    theme: litera
    css: styles.scss
    toc: true

editor: visual

